runtime: nodejs14 # or another supported version

instance_class: F2


handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /assets
  static_dir: src/assets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
